### ISSUE TITLE
能提供换成您代码里数据格式的脚本吗

### ISSUE THREAD

**Issue by so-bright** [Shank2358/NPMMR-Det#1]

**Comment by Shank2358** [comment]
> _No description provided._
刚写了一个，放在tools文件夹里了，你试试看，应该可以用。转换前DIOR数据的标注格式是VOC格式（xml），其他相同格式的数据应该也可以用。需要修改路径和类别名称的地方我在代码中注释了。DOTA数据集的格式看官方工具包，链接在readme里面给了。其他类型的格式可以自己学着写，不难的。
另外，这个问题已经解决完了，我close了~
