### ISSUE TITLE
测试结果不理想。

### ISSUE THREAD

**Issue by Cherich-GL** [Shank2358/NPMMR-Det#10]
![mmexport1651135202076](https://user-images.githubusercontent.com/95956260/165713330-cfe2ef55-fe54-4e22-ad08-7925f9d5ffba.png)
我的测试Map62点多，和您的结果差的太多。
![1651135378550](https://user-images.githubusercontent.com/95956260/165713784-23728352-603a-4b42-ab44-2ddf763d215f.jpg)
这是我的参数设置。

**Comment by Shank2358** [comment]
> ![mmexport1651135202076](https://user-images.githubusercontent.com/95956260/165713330-cfe2ef55-fe54-4e22-ad08-7925f9d5ffba.png) 我的测试Map62点多，和您的结果差的太多。 ![1651135378550](https://user-images.githubusercontent.com/95956260/165713784-23728352-603a-4b42-ab44-2ddf763d215f.jpg) 这是我的参数设置。

请问使用了预训练模型了吗？能否把loss曲线发给我康康。
另外这个是train还是trainval数据训练的结果，我这边对齐了跑一下康康。不应该查这么多呀，连baseline都没跑到，Airplane差了30个点。另外anchor您有聚类过吗，现在的anchor是trainval的？

**Comment by Cherich-GL** [comment]
您好，没有进行过anchor的聚类，使用的anchor就是您代码里的。
我使用的是train数据的训练结果。训练结果是67.9，测试结果是62点多。没有使用您的预训练模型。
![image](https://user-images.githubusercontent.com/95956260/165927025-817de161-8649-4b54-80aa-87edb4e74872.png)
这个初始学习率是对的吗 ，为什么第一个是零
您的预训练模型是这下面两个吗
![image](https://user-images.githubusercontent.com/95956260/165927358-5d8b1420-0cef-4094-96f9-e808498b9125.png)

**Comment by Shank2358** [comment]
> 您好，没有进行过anchor的聚类，使用的anchor就是您代码里的。 我使用的是train数据的训练结果。训练结果是67.9，测试结果是62点多。没有使用您的预训练模型。 ![image](https://user-images.githubusercontent.com/95956260/165927025-817de161-8649-4b54-80aa-87edb4e74872.png) 这个初始学习率是对的吗 ，为什么第一个是零 您的预训练模型是这下面两个吗 ![image](https://user-images.githubusercontent.com/95956260/165927358-5d8b1420-0cef-4094-96f9-e808498b9125.png)

预训练模型是我在ImageNet上面预训练好的Darknet53，检测模型是在这个基础上继续训练的，如果不用预训练模型而是从头开始训练的话需要训练更长时间，现在这种情况应该是模型没训练够的原因。DOTA数据集数据量比较大，可以从头训练差不多轮次就行，DIOR数据量比较小需要训练更久不用预先训练模型的话。

预训练模型是这个，
![image](https://user-images.githubusercontent.com/33946139/166091605-a84a393f-888d-412d-87fe-23eb845de0e1.png)
放到weight文件夹下，然后修改train.py的文件路径
![image](https://user-images.githubusercontent.com/33946139/166091625-85afc492-dc35-4d13-a8d4-a417b7afbac0.png)
这个在readme里面有说明

z这俩是训练好的模型，就是在DIOR上论文里最终的结果
![image](https://user-images.githubusercontent.com/33946139/166091632-00482f09-19b9-4940-a80a-029942c56fdd.png)
这个可以直接测试用，修改test.py文件的这里路径就行
![image](https://user-images.githubusercontent.com/33946139/166091652-3c4c1234-eec9-49b3-9d26-f99ad3b585e2.png)
