### ISSUE TITLE
可视化结果

### ISSUE THREAD

**Issue by lizifan123** [Shank2358/NPMMR-Det#13]
不好意思打扰您，请问您能分享一下关于SOBEL算子那里可视化的实现方法吗，万分感谢。我的邮箱是1041913859@qq.com

**Comment by Shank2358** [comment]
> 不好意思打扰您，请问您能分享一下关于SOBEL算子那里可视化的实现方法吗，万分感谢。我的邮箱是[1041913859@qq.com](mailto:1041913859@qq.com)

您好，感谢关注我们的工作。
直接在这里把out0,out90这些转成数组画出来就行
![image](https://user-images.githubusercontent.com/33946139/177779923-ff2873db-56d8-4105-8737-9b60ec13c4a3.png)
代码可以参考这样的
        import matplotlib.pyplot as plt
        out0_show = out0.permute(0, 2, 3, 1)detach().cpu() ##将顺序换为bs, H, W, C，转换到CPU，截断梯度
        out0_show = out0_show[0, :, :, 0:1]  ##取batch的第1个图
        plt.figure("Feature")  # 图像窗口名称
        plt.imshow(out0_show)
        plt.show()
您可以试试看，有问题随时交流，谢谢。

**Comment by lizifan123** [comment]
好的谢谢您
