### ISSUE TITLE
Prepare DIOR dataset 

### ISSUE THREAD

**Issue by TerrafYassin** [Shank2358/NPMMR-Det#14]
Thank you for this excellent work, please can you describe to me the steps to follow to prepare DIOR dataset with the scripts you used to arrive at the desired format to train your model please.

**Comment by Shank2358** [comment]
> 
This is the training label for DIOR. The test data set can be prepared in VOC format.
[train_DIOR.txt](https://github.com/Shank2358/NPMMR-Det/files/9222690/train_DIOR.txt)
Thank you.
