### ISSUE TITLE
Share DOTA dataset preprocessed

### ISSUE THREAD

**Issue by Ismaildata** [Shank2358/NPMMR-Det#15]
Hi , 
can you share with me , DOTA dataset preprocessed to be feeded to your model ?
Thank you.

**Comment by Shank2358** [comment]
> Hi , can you share with me , DOTA dataset preprocessed to be feeded to your model ? Thank you.



> Hi , can you share with me , DOTA dataset preprocessed to be feeded to your model ? Thank you.

Hi, You can refer to the official tutorials and processing tools of the DOTA dataset, see the following links:
https://github.com/CAPTAIN-WHU/DOTA_devkit
The data is too large and I can't upload it here. I also use the above tools to preprocess the data. The hyperparameters that need to be set in the tools are given in the paper.

Thank you.
