### ISSUE TITLE
 test this model on a single picture

### ISSUE THREAD

**Issue by TerrafYassin** [Shank2358/NPMMR-Det#16]
there is any demo to test this model on a single picture ?
Thank you.

**Comment by Shank2358** [comment]
You can refer to the code of these two parts.
https://github.com/Shank2358/GGHL/blob/main/evalR/evaluator_demo.py
https://github.com/Shank2358/GGHL/blob/main/demo..py

**Comment by Shank2358** [comment]
> You can refer to the code of these two parts.
> https://github.com/Shank2358/GGHL/blob/main/evalR/evaluator_demo.py
> https://github.com/Shank2358/GGHL/blob/main/demo..py

You can refer to the code of these two parts.
https://github.com/Shank2358/GGHL/blob/main/evalR/evaluator_demo.py
https://github.com/Shank2358/GGHL/blob/main/demo..py

**Comment by Shank2358** [comment]
> there is any demo to test this model on a single picture ? Thank you.

You can refer to the code of these two parts.
https://github.com/Shank2358/GGHL/blob/main/evalR/evaluator_demo.py
https://github.com/Shank2358/GGHL/blob/main/demo..py
