### ISSUE TITLE
"CONF_THRESH" value when testing on DIOR and DOTA datasets

### ISSUE THREAD

**Issue by terrafya** [Shank2358/NPMMR-Det#18]
Hello dear, 
what is the value of "CONF_THRESH" did you choose when testing your model on DOTA and DIOR datasets because in this repo you mentionned "CONF_THRESH":0.05 which generat a lot of false predictions?

**Comment by Shank2358** [comment]
> Hello dear, what is the value of "CONF_THRESH" did you choose when testing your model on DOTA and DIOR datasets because in this repo you mentionned "CONF_THRESH":0.05 which generat a lot of false predictions?

For higher mAP we usually set it to 0.05 or 0.01 according to the experience of VOC and COCO. For better visualization, it is recommended to set it to 0.2 or 0.3, but this will also lead to lower mAP results. Thank you.
