### ISSUE TITLE
please did you provide source code to visualize heatmap generated by your NP attention ?

### ISSUE THREAD

**Issue by terrafya** [Shank2358/NPMMR-Det#19]

**Comment by Shank2358** [comment]
Just use the matplotlib.

For example:

        import matplotlib.pyplot as plt
        import matplotlib.ticker as ticke
        plt.figure("Image") 
        ## 'feature' represent the output tensor of Conv layer
        feature_show = torch.max(feature, dim=-1)[0].squeeze(0).detach().cpu()
        plt.imshow(feature_show, cmap='jet' )

        ## resize the image to 1/N, N=stride, i.e., 8. 16, 32
        img = cv2.resize(img, dsize=None, fx=1 / N, fy=1 / N, interpolation=cv2.INTER_NEAREST)
        mask = feature_show* 255
        mask = np.uint8(np.concatenate((mask mask, mask), axis=2))
        mask= cv2.applyColorMap(mask_m, cv2.COLORMAP_HOT)
        add_img = cv2.addWeighted(img, 1, mask, 1, 0)  ## Weighted fusion feature mask and basemap
        plt.figure("Image")
        plt.imshow(add_img / 255, cmap='jet')

        cb = plt.colorbar() ##colorbar
        tick_locator = ticker.MaxNLocator(nbins=5) ##colorbar
        cb.locator = tick_locator
        cb.update_ticks()

        plt.show()

**Comment by Ismaildata** [comment]
what did you mean by mask_m?

**Comment by Shank2358** [comment]
> _m,

Sorry. It should be mask

**Comment by Shank2358** [comment]
> what did you mean by mask_m?

Sorry. It should be mask.

**Comment by Ismaildata** [comment]
code dosn't work for me , please can you send me correct code to show attention feature maps in backbone part after using NP attention mechanism ?
Thank you for your time.

**Comment by Ismaildata** [comment]
mask = np.uint8(np.concatenate((mask, mask, mask), axis=2))
  File "<__array_function__ internals>", line 6, in concatenate
numpy.AxisError: axis 2 is out of bounds for array of dimension 2
