### ISSUE TITLE
运行错误  torch.nn.modules.module.ModuleAttributeError: 'DataParallel' object has no attribute 'load_darknet_weights'

### ISSUE THREAD

**Issue by so-bright** [Shank2358/NPMMR-Det#3]
Let's use 2 GPUs!
Traceback (most recent call last):
  File "train.py", line 202, in <module>
    Trainer(weight_path=opt.weight_path, resume=opt.resume, gpu_id=opt.gpu_id).train()
  File "train.py", line 50, in __init__
    self.__load_model_weights(weight_path, resume)
  File "train.py", line 71, in __load_model_weights
    self.model.load_darknet_weights(weight_path) ## Single GPU
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 779, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'DataParallel' object has no attribute 'load_darknet_weights'

**Comment by Shank2358** [comment]
> Let's use 2 GPUs!
> Traceback (most recent call last):
> File "train.py", line 202, in
> Trainer(weight_path=opt.weight_path, resume=opt.resume, gpu_id=opt.gpu_id).train()
> File "train.py", line 50, in **init**
> self.__load_model_weights(weight_path, resume)
> File "train.py", line 71, in __load_model_weights
> self.model.load_darknet_weights(weight_path) ## Single GPU
> File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 779, in **getattr**
> type(self).**name**, name))
> torch.nn.modules.module.ModuleAttributeError: 'DataParallel' object has no attribute 'load_darknet_weights'

你的机器是单卡多卡的额
![image](https://user-images.githubusercontent.com/33946139/127157200-fda0f582-6909-4d97-b15c-3323bd698457.png)
看这里，把这个改一下如果是多卡，就是上面那行换成注释的那行

**Comment by so-bright** [comment]
出现了loss Nan的问题   我需要改小学习率吗

**Comment by Shank2358** [comment]
> 出现了loss Nan的问题 我需要改小学习率吗

这个loss NAN有可能有几种原因，只看这个我没法判断。我简单说一下思路，然后你根据这个排查一下：1）检查数据，是不是有异常的数值或者错误，这个是最容易出现NAN的原因，如果这个有问题，后面怎么调试网络或者学习率都没用，这个需要重点排查。我自己之前也踩过很多这个坑。dataset.py那个文件是可以单独运行的，你可以先排查这个。2）如果数据没问题了，再检查看看最终的loss输入和ground truth那里有没有问题，因为有的loss里面用到log或者除法，要记得分母不为0，log0也会错。3）检查学习率，如果我的代码里有warm up学习率是逐渐上升的，你可以看看学习率是到多少以后开始发散的，可以适当调小。4）和你的数据还有预训练模型的初始化有关系，我这边是默认使用预训练模型的，这个需要根据你的数据情况来确定。5）算法上，如果用NPMMR，在计算边缘和注意力那里有可能会出现梯度消失，这个问题等你前面都没问题了我再和你细说。

**Comment by Shank2358** [comment]
> > 出现了loss Nan的问题 我需要改小学习率吗
> 
> 这个loss NAN有可能有几种原因，只看这个我没法判断。我简单说一下思路，然后你根据这个排查一下：1）检查数据，是不是有异常的数值或者错误，这个是最容易出现NAN的原因，如果这个有问题，后面怎么调试网络或者学习率都没用，这个需要重点排查。我自己之前也踩过很多这个坑。dataset.py那个文件是可以单独运行的，你可以先排查这个。2）如果数据没问题了，再检查看看最终的loss输入和ground truth那里有没有问题，因为有的loss里面用到log或者除法，要记得分母不为0，log0也会错。3）检查学习率，如果我的代码里有warm up学习率是逐渐上升的，你可以看看学习率是到多少以后开始发散的，可以适当调小。4）和你的数据还有预训练模型的初始化有关系，我这边是默认使用预训练模型的，这个需要根据你的数据情况来确定。5）算法上，如果用NPMMR，在计算边缘和注意力那里有可能会出现梯度消失，这个问题等你前面都没问题了我再和你细说。

对了，配置文件的anchor你修改了吗？要根据你的数据集修改啊，那个默认的是在DIOR数据集上的anchor。看YOLO那个论文，kmeans聚类一下。
