### ISSUE TITLE
在NPMMR-Det/lib/cocoapi_linux/PythonAPI/   路径下没有make.sh 文件 

### ISSUE THREAD

**Issue by Cherich-GL** [Shank2358/NPMMR-Det#4]
您好打扰您了  在NPMMR-Det/lib/cocoapi_linux/PythonAPI/   路径下没有make.sh 文件  是不需要吗还是有什么问题，感谢您能够回答

**Comment by Shank2358** [comment]
> 您好打扰您了 在NPMMR-Det/lib/cocoapi_linux/PythonAPI/ 路径下没有make.sh 文件 是不需要吗还是有什么问题，感谢您能够回答

抱歉那个在makefile里面，终端输入这样：
python setup.py build_ext --inplace
如果是linux直接pip install pycocotools就行了
您试一下，还有问题就和我说，谢谢

**Comment by Cherich-GL** [comment]
好的  谢谢
