### ISSUE TITLE
在训练时出现WARNING:root:NaN or Inf found in input tensor.

### ISSUE THREAD

**Issue by Cherich-GL** [Shank2358/NPMMR-Det#5]
您好，我在训练时出现以下情况;

![image](https://user-images.githubusercontent.com/95956260/161471419-bcba31d6-45e9-41fe-a315-74f2770e9374.png)
希望能够得到您的解答 万分感谢

**Comment by Shank2358** [comment]
> 您好，我在训练时出现以下情况;
> 
> ![image](https://user-images.githubusercontent.com/95956260/161471419-bcba31d6-45e9-41fe-a315-74f2770e9374.png) 希望能够得到您的解答 万分感谢

哈喽，也许可以先排查一下数据读取和格式是否正确~有可能是数据转换出错了呢，也有可能是分母除0或者log里面是0的原因。

**Comment by tzhhh02** [comment]
您好，我在训练模型的时候也出现了这个问题，请问您是怎么解决的呢？
