### ISSUE TITLE
MSCOCO 格式 将 .json 文件放在 ./data 文件夹中。

### ISSUE THREAD

**Issue by Cherich-GL** [Shank2358/NPMMR-Det#6]
您好，我基础较差 (2) MSCOCO 格式    将 .json 文件放在 ./data 文件夹中。意思是将dior的xml文件转换成json文件吗？希望能得到您的回复，万分感谢！！！

**Comment by Shank2358** [comment]
> 您好，我基础较差 (2) MSCOCO 格式 将 .json 文件放在 ./data 文件夹中。意思是将dior的xml文件转换成json文件吗？希望能得到您的回复，万分感谢！！！

哈喽， 如果有xml的话直接用VOC格式读取就好了呀，把xml转成train.txt就行啦，转换的脚本代码是/tools/xml2txt.py这个
1）2）意思是二选一的意思，如果是COCO格式就用后面一种~~
有啥不会的都可以和我反馈，我们一起解决呀~~
谢谢

**Comment by Shank2358** [comment]
[train.txt](https://github.com/Shank2358/NPMMR-Det/files/8415773/train.txt)

这是我转换后的DIOR数据标签，你可以康康这个~

**Comment by Cherich-GL** [comment]
[test.txt](https://github.com/Shank2358/NPMMR-Det/files/8416138/test.txt)
很谢谢您，您看这是我转换的dior数据标签，并且把这个两个txt放在了data文件夹下，这样是对的吗？

**Comment by Shank2358** [comment]
> [test.txt](https://github.com/Shank2358/NPMMR-Det/files/8416138/test.txt) 很谢谢您，您看这是我转换的dior数据标签，并且把这个两个txt放在了data文件夹下，这样是对的吗？

嗯嗯，只需要train.txt就好啦~~放在data文件夹下。
然后config.py文件里有这样一行
DATA_PATH = "/mnt/Datasets/DIOR/"
这个是测试数据的路径（修改成你的测试数据路径），就是标准的VOC格式
比如像这样
![image](https://user-images.githubusercontent.com/33946139/161711551-dc9e7a26-0eca-4c62-96b0-c37c75b86dcb.png)
ImageSets里面是文件名字，长这样，就是和VOC数据集一毛一样的
![image](https://user-images.githubusercontent.com/33946139/161711688-0e47c8fe-85ea-4b0e-aab1-0ddf7650b1da.png)
然后再试试看可以运行吗
[test.txt](https://github.com/Shank2358/NPMMR-Det/files/8416306/test.txt)

**Comment by Shank2358** [comment]
> [test.txt](https://github.com/Shank2358/NPMMR-Det/files/8416138/test.txt) 很谢谢您，您看这是我转换的dior数据标签，并且把这个两个txt放在了data文件夹下，这样是对的吗？

这是VOC格式的xml标签
[Annotations_VOC.zip](https://github.com/Shank2358/NPMMR-Det/files/8416359/Annotations_VOC.zip)

这是COCO的json格式标签
[json_gt.zip](https://github.com/Shank2358/NPMMR-Det/files/8416343/json_gt.zip)

图像就是原始数据集下载下来那样的，直接用就行
