### ISSUE TITLE
在训练过程中map始终为0

### ISSUE THREAD

**Issue by Cherich-GL** [Shank2358/NPMMR-Det#7]
![image](https://user-images.githubusercontent.com/95956260/162114304-4cfd057e-1558-4957-9a56-103e3899b733.png)
我的 weight_path用的是您网盘里的NPMMRDet_darknet_pretrained.weights      
在运行test.py时 会出现
![image](https://user-images.githubusercontent.com/95956260/162128273-af793524-f10d-499d-b5bb-fcabd2be0c46.png)
在训练完成时会在路径下产生test.json文件吗

**Comment by Shank2358** [comment]
> ![image](https://user-images.githubusercontent.com/95956260/162114304-4cfd057e-1558-4957-9a56-103e3899b733.png) 我的 weight_path用的是您网盘里的NPMMRDet_darknet_pretrained.weights 在运行test.py时 会出现 ![image](https://user-images.githubusercontent.com/95956260/162128273-af793524-f10d-499d-b5bb-fcabd2be0c46.png) 在训练完成时会在路径下产生test.json文件吗

train.py的这里
![image](https://user-images.githubusercontent.com/33946139/162184928-dca4bf92-8c9e-4713-b00b-9fa94f607965.png)
意思是epoch>80开始验证，每5个epoch验证一次，在80 epoch之前是不进行验证的mAP直接给0值。
需要修改一下这里。

然后label的json文件路径不对，在coco_eval.py的这里有test.json路径设置
![image](https://user-images.githubusercontent.com/33946139/162185328-0f2ad7ad-8202-4a6b-bf85-adde3c8b5c98.png)
或者您应该新建并在/mnt/DIOR/json_gt文件夹下放入test.json

谢谢

**Comment by Cherich-GL** [comment]
好的 谢谢您  非常感谢您耐心的答复。
