### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 0)

### ISSUE THREAD

**Issue by Cherich-GL** [Shank2358/NPMMR-Det#8]
您好我在训练过程中会出现以下问题，我查找一些解决办法。但是还是没有解决。
![image](https://user-images.githubusercontent.com/95956260/162354030-1b1e2306-c0bc-456b-afae-176e2c9d8c2c.png)

**Comment by Shank2358** [comment]
> 您好我在训练过程中会出现以下问题，我查找一些解决办法。但是还是没有解决。 ![image](https://user-images.githubusercontent.com/95956260/162354030-1b1e2306-c0bc-456b-afae-176e2c9d8c2c.png)

图像没读对，进来的是空的
